kind: Service
apiVersion: v1
metadata:
  name: nginx-app-service
  labels:
    app: nginx-example
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: nginx-example