CREATE TABLE IF NOT EXISTS notes (
    id SERIAL PRIMARY KEY,
    text_content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notes_completed ON notes (is_completed);